export const title = '# Tailwind CSS';
export const content1 = 'Tailwind CSS 是一个实用优先的 CSS 框架，与 Next.js 配合得非常好。';
export const content2 = '## 安装 Tailwind';
export const content3 = '安装 Tailwind CSS 包并运行 init 命令以生成 tailwind.config.js 和 postcss.config.js 文件：';
export const content3Code = `~~~
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p`;
export const content4 = '## 配置 Tailwind';
export const content5 = '在 Tailwind 配置文件中，添加将使用 Tailwind 类名的文件路径：';
export const content5Code = `~~~tailwind.config.ts

import type { Config } from 'tailwindcss'
 
const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}', // Note the addition of the \`app\` directory.
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
 
    // Or if using \`src\` directory:
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config`;
export const content6 = '您不需要修改postcss.config.js。';
export const content7 = '## 导入样式';
export const content8 = '添加 Tailwind CSS 指令，Tailwind 将使用它来将其生成的样式注入到应用程序中的全局样式表，例如：';
export const content8Code = `~~~app/globals.css

@tailwind base;
@tailwind components;
@tailwind utilities;`;
export const content9 = '在根布局（app/layout.tsx）中，导入 globals.css 样式表,从而将样式应用于应用程序中的每个路由。';
export const content9Code = `~~~app/layout.tsx;

import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`;
export const content10 = '## 使用类(classes)';
export const content11 = '安装 Tailwind CSS 并添加全局样式后，您可以在应用程序中使用 Tailwind 的实用程序类。';
export const content11Code = `~~~app/pages.tsx

export default function Page() {
  return <h1 className="text-3xl font-bold underline">Hello, Next.js!</h1>
}`;
export const content12 = '## 与 Turbopack 一起使用';
export const content13 = '从 Next.js 13.1 开始，Turbopack 支持 Tailwind CSS 和 PostCSS。';

